src/Entity/Propriete.php
<?php

namespace App\Entity;

use App\Repository\ProprieteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProprieteRepository::class)]
class Propriete
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 25)]
    private ?string $type = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $prix = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $surface = null;

    #[ORM\Column]
    private ?int $chambres = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 100)]
    private ?string $ville = null;

    #[ORM\Column(length: 5)]
    private ?string $codepostal = null;

    #[ORM\Column]
    private ?float $latitude = null;

    #[ORM\Column]
    private ?float $longitude = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_update = null;

    /**
     * @var Collection<int, Photo>
     */
    #[ORM\OneToMany(targetEntity: Photo::class, mappedBy: 'propriete', orphanRemoval: true)]
    private Collection $photo;

    /**
     * @var Collection<int, Accessoire>
     */
    #[ORM\ManyToMany(targetEntity: Accessoire::class, inversedBy: 'propriete')]
    private Collection $accessoires;

    /**
     * @var Collection<int, Contact>
     */
    #[ORM\OneToMany(targetEntity: Contact::class, mappedBy: 'propriete')]
    private Collection $contact;

    #[ORM\ManyToOne(inversedBy: 'propriete')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $userid = null;

    public function __construct()
    {
        $this->photo = new ArrayCollection();
        $this->accessoires = new ArrayCollection();
	$this->contact = new ArrayCollection();
	$this->date_creation = new \DateTime();
	$this->date_update = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getSurface(): ?string
    {
        return $this->surface;
    }

    public function setSurface(string $surface): static
    {
        $this->surface = $surface;

        return $this;
    }

    public function getChambres(): ?int
    {
        return $this->chambres;
    }

    public function setChambres(int $chambres): static
    {
        $this->chambres = $chambres;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodepostal(): ?string
    {
        return $this->codepostal;
    }

    public function setCodepostal(string $codepostal): static
    {
        $this->codepostal = $codepostal;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(\DateTimeInterface $date_update): static
    {
        $this->date_update = $date_update;

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhoto(): Collection
    {
        return $this->photo;
    }

    public function addPhoto(Photo $photo): static
    {
        if (!$this->photo->contains($photo)) {
            $this->photo->add($photo);
            $photo->setPropriete($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): static
    {
        if ($this->photo->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getPropriete() === $this) {
                $photo->setPropriete(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function onPrePersist()
    {
	    $this->date_update = new \DateTime();

    }

    /**
     * @return Collection<int, Accessoire>
     */
    public function getAccessoires(): Collection
    {
        return $this->accessoires;
    }

    public function addAccessoire(Accessoire $accessoire): static
    {
        if (!$this->accessoires->contains($accessoire)) {
            $this->accessoires->add($accessoire);
        }

        return $this;
    }

    public function removeAccessoire(Accessoire $accessoire): static
    {
        $this->accessoires->removeElement($accessoire);

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContact(): Collection
    {
        return $this->contact;
    }

    public function addContact(Contact $contact): static
    {
        if (!$this->contact->contains($contact)) {
            $this->contact->add($contact);
            $contact->setPropriete($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): static
    {
        if ($this->contact->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getPropriete() === $this) {
                $contact->setPropriete(null);
            }
        }

        return $this;
    }

    public function getUserid(): ?User
    {
        return $this->userid;
    }

    public function setUserid(?User $userid): static
    {
        $this->userid = $userid;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $prenom = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    /**
     * @var Collection<int, Propriete>
     */
    #[ORM\OneToMany(targetEntity: Propriete::class, mappedBy: 'userid', orphanRemoval: true)]
    private Collection $propriete;

    public function __construct()
    {
        $this->propriete = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection<int, Propriete>
     */
    public function getPropriete(): Collection
    {
        return $this->propriete;
    }

    public function addPropriete(Propriete $propriete): static
    {
        if (!$this->propriete->contains($propriete)) {
            $this->propriete->add($propriete);
            $propriete->setUserid($this);
        }

        return $this;
    }

    public function removePropriete(Propriete $propriete): static
    {
        if ($this->propriete->removeElement($propriete)) {
            // set the owning side to null (unless already changed)
            if ($propriete->getUserid() === $this) {
                $propriete->setUserid(null);
            }
        }

        return $this;
    }
}

src/Controller/FrontendController.php
<?php

namespace App\Controller;

use App\Entity\Propriete;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

use App\Repository\ProprieteRepository;

class FrontendController extends AbstractController
{
   
    public function index(EntityManagerInterface $entityManager, PaginatorInterface $paginator, Request $request): Response
    {
	$queryBuilder = $entityManager->getRepository(Propriete::class)->createQueryBuilder('p');

        $pagination = $paginator->paginate(
            $queryBuilder->getQuery(),
            $request->query->getInt('page', 1), // Current page number, default to 1
            10 // Number of items per page
        );

	    return $this->render('frontend/index.html.twig', [
		'pagination' => $pagination,
		'controller_name' => 'FrontendController',
        ]);
    }

    
    public function listeproprietes(EntityManagerInterface $entityManager, PaginatorInterface $paginator, Request $request): Response
    {
	$queryBuilder = $entityManager->getRepository(Propriete::class)->createQueryBuilder('p');

        $pagination = $paginator->paginate(
            $queryBuilder->getQuery(),
            $request->query->getInt('page', 1), // Current page number, default to 1
            10 // Number of items per page
        );    
	    
	return $this->render('frontend/listeproprietes.html.twig', [
 		'pagination' => $pagination,
        ]);
    }
   
     public function listByPriceRange(float $minPrice, float $maxPrice, ProprieteRepository $proprieteRepository): Response
    {
	   if ($minPrice < 0 || $maxPrice < $minPrice) {
            throw $this->createNotFoundException('La plage de prix n\'est pas valide.');
        }
	  
	   
	    $proprietes = $proprieteRepository->findPropertyByRangeOfPrice($minPrice, $maxPrice);

        return $this->render('frontend/list_by_price_range.html.twig', [
            'proprietes' => $proprietes,
            'minPrice' => $minPrice,
            'maxPrice' => $maxPrice,
        ]);
    }



   #[Route('/proprietedetail/{id}', name:'propriete_detail')]
   public function proprietedetail(int $id=null,ProprieteRepository $proprieteRepository): Response
   {    
   
	   $propriete = $proprieteRepository->findProprieteById($id);

	

	   return $this->render('frontend/propriete_detail.html.twig', [
		   'propriete' => $propriete,
	   ]);
   }

}

templates/frontend/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil - We Take Care{% endblock %}

{% block body %}
    <div class="jumbotron">
        <h2 class="display-4">We Take Care - WTK</h2>
        <p class="lead">Découvrez nos propriétés exclusives et trouvez votre futur chez-vous.</p>
        <hr class="my-4">
        <p>Explorez notre sélection de propriétés haut de gamme.</p>
   
    <div class="overflow-x-auto">
        <table class="min-w-full bg-white">
        <thead>
            <tr>
                <th class="px-4 py-2">Id</th>
                <th class="px-4 py-2">Photo Principale</th>
                <th class="px-4 py-2">Titre</th>
                <th class="px-4 py-2">Type</th>
                <th class="px-4 py-2">Prix</th>
                <th class="px-4 py-2">Surface</th>
                <th class="px-4 py-2">Ville</th>
                <th class="px-4 py-2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for propriete in pagination %}
                <tr class="bg-gray-100">
                    <td class="border px-4 py-2">{{ propriete.id }}</td>
                    <td class="border px-4 py-2">
                        {% set photoPrincipale = propriete.getPhoto|filter(photo => photo.principale)|first %}
                        {% if photoPrincipale %}
                            <img src="{{ asset(photoPrincipale.filename) }}" alt="Photo Principale" style="max-width: 100px; max-height: 100px;">
                        {% else %}
                            <span>Pas de photo</span>
                        {% endif %}
                    </td>
                    <td class="border px-4 py-2">{{ propriete.titre }}</td>
                    <td class="border px-4 py-2">{{ propriete.type }}</td>
                    <td class="border px-4 py-2">{{ propriete.prix|number_format(0, ',', ' ') }} €</td>
                    <td class="border px-4 py-2">{{ propriete.surface }} m²</td>
                    <td class="border px-4 py-2">{{ propriete.ville }}</td>
                    <td class="border px-4 py-2">
                        <a href="{{ path('proprietedetail', {'id': propriete.id}) }}" class="btn btn-primary">Voir détails</a>
                    </td>
                </tr>
            {% else %}
	<tr>
                    <td colspan="8" class="border px-4 py-2 text-center">Aucune propriété trouvée.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
  </div>
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}

templates/frontend/list_by_price_range.html.twig
{% extends 'base.html.twig' %}

{% block title %}Propriétés entre {{ minPrice|number_format(0, ',', ' ') }} € et {{ maxPrice|number_format(0, ',', ' ') }} €{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
<div class="container mx-auto p-4">
    <h2 class="text-2xl font-bold text-primary mb-4">Propriétés entre {{ minPrice|number_format(0, ',', ' ') }} € et {{ maxPrice|number_format(0, ',', ' ') }} €</h2>
    <div class="overflow-x-auto">
        <table class="min-w-full bg-white">
            <thead>
                <tr>
                    <th class="px-4 py-2">ID</th>
                    <th class="px-4 py-2">Photo Principale</th>
                    <th class="px-4 py-2">Titre</th>
                    <th class="px-4 py-2">Type</th>
                    <th class="px-4 py-2">Prix</th>
                    <th class="px-4 py-2">Surface</th>
                    <th class="px-4 py-2">Ville</th>
                    <th class="px-4 py-2">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for propriete in proprietes %}
                    <tr class="bg-gray-100">
                        <td class="border px-4 py-2">{{ propriete.id }}</td>
                        <td class="border px-4 py-2">
                            {% set photoPrincipale = propriete.photo|filter(photo => photo.principale)|first %}
                            {% if photoPrincipale %}
                                <img src="{{ asset(photoPrincipale.filename) }}" alt="Photo Principale" class="max-w-xs max-h-xs">
                            {% else %}
                                <span>Pas de photo</span>
                            {% endif %}
                        </td>
                        <td class="border px-4 py-2">{{ propriete.titre }}</td>
                        <td class="border px-4 py-2">{{ propriete.type }}</td>
                        <td class="border px-4 py-2">{{ propriete.prix|number_format(0, ',', ' ') }} €</td>
                        <td class="border px-4 py-2">{{ propriete.surface }} m²</td>
                        <td class="border px-4 py-2">{{ propriete.ville }}</td>
                        <td class="border px-4 py-2">
                            <a href="{{ path('proprietedetail', {'id': propriete.id}) }}" class="btn btn-primary text-primary bg-secondary px-4 py-2 rounded">Voir détails</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8" class="border px-4 py-2 text-center">Aucune propriété trouvée dans cette plage de prix.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/frontend/listeproprietes.html.twig
{# templates/propriete/listeproprietes.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Liste des Propriétés{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}


{% block body %}
    {# Formulaire de recherche #}
    <form action="{{ path('findPropertyByRangeOfPrice') }}" method="GET" class="mb-8 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full md:w-1/4 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="minPrice">
                    Prix minimum
                </label>
                <input class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="minPrice" name="minPrice" type="number" placeholder="Prix min">
            </div>
            <div class="w-full md:w-1/4 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="maxPrice">
                    Prix maximum
                </label>
                <input class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="maxPrice" name="maxPrice" type="number" placeholder="Prix max">
            </div>
            <div class="w-full md:w-1/4 px-3 mb-6 md:mb-0 flex items-end">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Rechercher
                </button>
            </div>
        </div>
    </form>

<div class="container mx-auto p-4">
    <h2 class="text-2xl font-bold text-primary mb-4">Nos Propriétés</h2>
    <div class="overflow-x-auto">
	<table class="min-w-full bg-white">
        <thead>
            <tr>
                <th class="px-4 py-2">Id</th>
                <th class="px-4 py-2">Photo Principale</th>
                <th class="px-4 py-2">Titre</th>
                <th class="px-4 py-2">Type</th>
                <th class="px-4 py-2">Prix</th>
                <th class="px-4 py-2">Surface</th>
                <th class="px-4 py-2">Ville</th>
                <th class="px-4 py-2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for propriete in pagination %}
                <tr class="bg-gray-100">
                    <td class="border px-4 py-2">{{ propriete.id }}</td>
                    <td class="border px-4 py-2">
                        {% set photoPrincipale = propriete.getPhoto|filter(photo => photo.principale)|first %}
                        {% if photoPrincipale %}
                            <img src="{{ asset(photoPrincipale.filename) }}" alt="Photo Principale" style="max-width: 100px; max-height: 100px;">
                        {% else %}
                            <span>Pas de photo</span>
                        {% endif %}
                    </td>
                    <td class="border px-4 py-2">{{ propriete.titre }}</td>
                    <td class="border px-4 py-2">{{ propriete.type }}</td>
                    <td class="border px-4 py-2">{{ propriete.prix|number_format(0, ',', ' ') }} €</td>
                    <td class="border px-4 py-2">{{ propriete.surface }} m²</td>
                    <td class="border px-4 py-2">{{ propriete.ville }}</td>
                    <td class="border px-4 py-2">
                        <a href="{{ path('proprietedetail', {'id': propriete.id}) }}" class="btn btn-primary">Voir détails</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8" class="border px-4 py-2 text-center">Aucune propriété trouvée.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
  </div>

    <div class="mt-4">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}

templates/frontend/propriete_detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ propriete.titre }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"/>
{% endblock %}

{% block body %}
<div class="bg-slate-800 text-gray-100">
    <h2 class="text-3xl font-bold mb-6 text-green-400">{{ propriete.titre }}</h2>

    <div class="flex flex-col md:flex-row gap-8">
        <div class="md:w-1/3">
            <div id="proprieteCarousel" class="carousel slide shadow-lg rounded-lg overflow-hidden" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for photo in propriete.photo %}
                        <div class="carousel-item {% if photo.isPrincipale %}active{% endif %}">
                            <img src="{{ asset(photo.filename) }}" class="d-block w-100" alt="Photo {{ loop.index }}">
                        </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#proprieteCarousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Precedente</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#proprieteCarousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Suivante</span>
                </button>
            </div>
	    <div id="map" class="h-64 rounded-lg shadow-lg"></div>
        </div>
	<div class="md:w-1/3">
        <div class="md:w-1/3 bg-slate-700 p-6 rounded-lg shadow-md">
            <h3 class="text-xl font-semibold mb-4 text-green-300">Détails</h3>
            <p class="mb-4"><strong class="text-yellow-400">Prix : </strong>{{ propriete.prix|number_format(0, ',', ' ') }} €</p>
             <ul class="mb-5">
            <li>Type: {{ propriete.type }}</li>
            <li>Surface: {{ propriete.surface }} m²</li>
            <li>Chambres: {{ propriete.chambres }}</li>
            <li>Adresse: {{ propriete.adresse }}</li>
            <li>Ville: {{ propriete.ville }}</li>
            <li>Code Postal: {{ propriete.codepostal }}</li>
            <li>Latitude: {{ propriete.latitude }}</li>
            <li>Longitude: {{ propriete.longitude }}</li>
            <li>Date de Création: {{ propriete.dateCreation|date('d-m-Y H:i') }}</li>
            <li>Date de Mise à Jour: {{ propriete.dateUpdate|date('d-m-Y H:i') }}</li>
        	</ul>
	   </div> 
	    <div class="bg-slate-700 p-6 rounded-lg shadow-md">
		<h4 class="text-lg font-semibold mb-2 text-green-300">Accessoires</h4>
            	<ul>
                {% for accessoire in propriete.accessoires %}
                    <li>{{ accessoire.nom }}</li>
                {% endfor %}
            	</ul>
           </div>
	</div>
    </div>

    <div class="mt-8">
        <h3 class="text-xl font-semibold mb-4 text-green-300">Description</h3>
        <p class="text-gray-300">{{ propriete.description }}</p>
    </div>

    <div class="mt-8">
            <h3 class="text-xl font-semibold mb-4 text-green-300">Demandes de contact</h3>
            <ul class="bg-slate-700 rounded-lg shadow-md divide-y divide-slate-600">
                {% for contact in propriete.contact %}
                    <li class="p-4">
                        <strong class="text-yellow-400">{{ contact.nom }}</strong>
			<span class="text-gray-400">({{ contact.email }} | {{contact.phone}})</span>
           		<p class="mt-2 text-gray-300">Message : {{ contact.message }}</p>
                    </li>
                {% else %}
                    <li class="p-4 text-gray-400">Aucune demande de contact pour cette propriété.</li>
                {% endfor %}
            </ul>
        </div>
</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script>
        $(document).addEventListener('DOMContentLoaded',function(){
            $('#proprieteCarousel').slick({
                dots: true,
                infinite: true,
                speed: 500,
                fade: true,
                cssEase: 'linear'
            });
	   
	    // Initialisation de la carte
        setTimeout(function(){
	var mapElement = document.getElementById('map');
        if (mapElement) {
            var map = L.map('map').setView([{{ propriete.latitude }}, {{ propriete.longitude }}], 13);
            
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);
            
            // Ajout du marqueur
            L.marker([{{ propriete.latitude }}, {{ propriete.longitude }}])
                .addTo(map)
                .bindPopup("{{ propriete.titre }}")
                .openPopup();
        }},100);

        });
    </script>
{% endblock %}